/*Challenge link:https://leetcode.com/problems/find-the-difference/description/
Question:
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
*/

//***************Solution********************
//method 1
public class Solution {
    public char FindTheDifference(string s, string t) {
        //check length different
        //loop each character in string s
        //count of current character at s and t when equal to c, compare both result
        if (s.Length > t.Length) {
            foreach (char c in s) {
                if (s.Count(x => x == c) > t.Count(x => x == c)) {
                    return c;
                }
            }
        }
        
        //do the same thing but opposite.
        if (t.Length > s.Length) {
            foreach (char c in t) {
                if (t.Count(x => x == c) > s.Count(x => x == c)) {
                    return c;
                }
            }
        }
        return ' ';
    }
}

//method 2
public class Solution {
    public char FindTheDifference(string s, string t) {
        int n = t.Length;
        char c = t[n - 1];
        for (int i = 0; i < n - 1; ++i){
            c ^= s[i];
            c ^= t[i];
        }
        return c;
    }
}
